config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :groups, except: %i[edit update] do
    resources :memberships, only: %i[new create destroy]
    resources :bills, only: %i[new create]
  end
  get 'activities', to: 'bills#index'
  namespace :users do
	  get 'signup', to: 'registrations#new'
    post 'signup', to: 'registrations#create'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

end

app/models/membership.rb
# == Schema Information
#
# Table name: memberships
#
#  id         :integer          not null, primary key
#  group_id   :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Membership < ApplicationRecord

  belongs_to :group
  belongs_to :user

  validates :user_id, presence: true, uniqueness: {scope: %i[group_id user_id] }

  before_destroy :validate_owner_of_group
  after_destroy :destroy_associated_bill_splits

  private

  def validate_owner_of_group
    if user == group.owner
      errors.add(:base, I18n.t('memberships.destroy.not_allowed_to_destroy_group_owner'))
    end
  end

  # Deletes associated bill shares once membership is removed from the group.
  #
  # @return [void]
  def destroy_associated_bill_splits
    group.splits.where(recipient_id: user_id).destroy_all
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  # Renders new form for <tt>Memberships</tt>.
  #
  # @get_params :id
  #
  # @verb GET
  #
  # @accepts HTML
  def new
    @membership = Membership.new
  end

  # Creates new <tt>Membership</tt>.
  #
  # @get_params :id
  #
  # @verb POST
  #
  # @accepts HTML
  def create
    @membership = group.memberships.build(membership_params)
    if @membership.save
      flash[:notice] = t('.member_added')
      redirect_to group_path(group.id)
    else
      render :new
    end
  end

  # Deletes <tt>Membership</tt>.
  #
  # @get_params :id
  #
  # @verb DELETE
  #
  # @accepts HTML
  def destroy
    if membership.destroy
      flash[:success] = t('.membership_destroyed')
      redirect_to group_path(group.id)
    else
      flash[:alert] = t('.not_allowed_to_destroy_group_owner')
      redirect_to group_path(group.id)
    end
  end

  private

  # Finds <tt>Membership</tt> using params id.
  #
  # @return [Membership]
  def membership
    @membership ||= Membership.find params[:id] if params[:id]
  end

  # Finds <tt>Group</tt> using params id.
  #
  # @return [Group]
  def group
    @group ||= Group.find params[:group_id] if params[:group_id]
  end

  # Only allow a list of trusted parameters through params white listing.
  def membership_params
    params.require(:membership).permit(:user_id)
  end

end

app/views/memberships/new.html.haml
.container
  .row.justify-content-center
    .col-10
      = render 'shared/errors', obj: @membership
      = form_with(model: @membership, url: group_memberships_path(group_id: params[:group_id]), class: 'shadow p-3 mb-3 bg-info rounded', local:true)  do |f|
        .form-group.row
          = f.label :user_id, class: 'col-2 col-form-label text-light'
          .col-10
            = f.select :user_id, members_not_included_in_group(params[:group_id]), {}, { class: 'form form-group form-control' }
        .form-group.row.justify-content-center
          = f.submit t('general.submit'), class: 'btn btn-outline-light btn-lg'
    = link_to '[ Cancel and return to Membership listing ]', group_path(params[:group_id]), class: 'text-info'