config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :groups, except: %i[edit update] do
    resources :memberships, only: %i[new create destroy]
    resources :bills, only: %i[new create]
  end
  get 'activities', to: 'bills#index'
  namespace :users do
	  get 'signup', to: 'registrations#new'
    post 'signup', to: 'registrations#create'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string
#  owner_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Group < ApplicationRecord

  validates :name, presence: true, uniqueness: { scope: :owner_id }

  belongs_to :owner, class_name: 'User'
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
  has_many :bills, dependent: :destroy
  has_many :splits, through: :bills

  after_create :add_owner_membership

  # Returns details of amount lent/owed by pair members of group.
  #
  # @param args [Hash]
  #   * option user_id [Integer] Logged in member id(unique identifier)
  #   * option member_id [Integer] Other Member id(unique identifier) of Group
  #
  # @return [String]
  def amount_owed_or_lent_by_member(user_id, member_id)
    user_shares = bill_shares_between_members(user_id, member_id)
    member_shares = bill_shares_between_members(member_id, user_id)
    if user_shares > member_shares
      I18n.t('general.amount_lent', amount: ((user_shares - member_shares)))
    elsif user_shares < member_shares
      I18n.t('general.amount_owes', amount: ((member_shares - user_shares)))
    else
      I18n.t('general.no_amount_shared')
    end
  end

  private

  # Add owner as a default member of group.
  #
  # @return [void]
  def add_owner_membership
  	memberships.create(group_id: id, user_id: owner_id)
  end

  # Shares of the Bill among the members of group.
  #
  # @param args [Hash]
  #   * option creditor_id [Integer]
  #   * option member_type [String]
  #   * option recipient_id [Integer]
  #
  # @return [Integer]
  def bill_shares_between_members(creditor_id, debtor_id)
    splits.joins(:bill).where(
      bill: { author_id: creditor_id },
      member_type: 'recipient',
      recipient_id: debtor_id
    ).sum(:amount)&.round(2)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :require_user
  before_action :require_same_user, only: %i[destroy]

  # Renders list of <tt>Groups</tt>.
  #
  # @verb GET
  #
  # @accepts HTML
  def index
    @groups = current_user.groups.paginate(page: params[:page], per_page: 5)
  end

  # Renders new form for <tt>Group</tt>.
  #
  # @get_params :id
  #
  # @verb GET
  #
  # @accepts HTML
  def new
    @group = Group.new
  end

  # Creates new <tt>Group</tt>.
  #
  # @get_params :id
  #
  # @verb POST
  #
  # @accepts HTML
  def create
    @group = current_user.owned_group.build
    @group.assign_attributes(group_params)
    if @group.save
      redirect_to group_path(group)
    else
      render :new
    end
  end

  # Renders groups's <tt>Memberships</tt> details.
  #
  # @get_params :id
  #
  # @verb GET
  #
  # @accepts HTML
  def show
    @members = group.members.paginate(page: params[:page], per_page: 5)
  end

  # Deletes <tt>Group</tt>.
  #
  # @get_params :id
  #
  # @verb DELETE
  #
  # @accepts HTML
  def destroy
    if group.destroy
      flash[:success] = t('.group_destroyed')
      redirect_to groups_path
    else
      flash.now[:alert] = t('.unable_to_delete')
      render :index
    end
  end

  private

  # Finds <tt>Group</tt> using params id.
  #
  # @return [Group]
  def group
    @group ||= Group.find params[:id]
  end

  # Only allow a list of trusted parameters through params white listing.
  def group_params
    params.require(:group).permit(:name)
  end

  # Renders 'access denied' if logged in user is not an owner of group.
  def require_same_user
    if current_user != group.owner
      flash[:alert] = t('general.access_denied')
    end
  end

end

app/views/groups/index.html.haml
.container
  .row.d-flex.justify-content-center  
    = link_to 'Add new Group', new_group_path, class: 'btn btn-outline-success'
  .row.d-flex.justify-content-center
    - @groups.each do |group|
      .col-8.mt-4
        .card.text-center.shadow.mb-5.bg-white.rounded
          .card-header.font-italic
            = link_to group.name, group
          .card-body
            %p.card-text= "Memberships:#{group.members.count}"
            = link_to 'View Group Details', group, class: 'btn btn-outline-success'
            - if logged_in?
              - if group.owner == current_user
                = link_to 'Delete Profile', group_path(current_user), method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure you want to delete the group and associated group member?' }
          .card-footer.text-muted
            %small
              Joined #{time_ago_in_words(group.created_at)}ago
.flickr_pagination.mb-4
  = will_paginate @groups, container: false

app/views/groups/new.html.haml
.container
  .row.justify-content-center
    .col-10
      = render 'shared/errors', obj: @group
      = form_with(model: @group, class: 'shadow p-3 mb-3 bg-info rounded', local:true)  do |f|
        .form-group.row
          = f.label :name, class: 'col-2 col-form-label text-light'
          .col-10
            = f.text_field :name, class: 'form-control shadow rounded', placeholder: 'Enter a Group name'
        .form-group.row.justify-content-center
          = f.submit t('general.submit'), class: 'btn btn-outline-light btn-lg'
    = link_to '[ Cancel and return to Group listing ]', groups_path, class: 'text-info'

app/views/groups/show.html.haml
.container
  .row.d-flex.justify-content-center
    .ml-4
      = link_to t('general.add_new_member'), new_group_membership_path(group_id: @group.id), class: 'btn btn-outline-success'
    .ml-4
      = link_to t('general.add_new_bill'), new_group_bill_path(group_id: @group.id), class: 'btn btn-outline-success'
  .row.d-flex.justify-content-center
    - @members.each do |member|
      .col-8.mt-4
        .card.text-center.shadow.mb-5.bg-white.rounded
          .card-header.font-italic
            = member.name
          - if member != current_user
            .card-body.text-success
              %p.card-text= @group.amount_owed_or_lent_by_member(current_user.id, member.id)
          - if logged_in? && @group.owner != member
            = link_to t('general.remove_member'), group_membership_path(id: @group.memberships.find_by(user_id: member.id)&.id, group_id: @group), method: :delete, class: 'btn btn-outline-danger', data: { confirm: t('general.member_removal_confirmation') }
          .card-footer.text-muted
            %small
              Joined #{time_ago_in_words(member.created_at)}ago
.flickr_pagination.mb-4
  = will_paginate @members, container: false