config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :groups, except: %i[edit update] do
    resources :memberships, only: %i[new create destroy]
    resources :bills, only: %i[new create]
  end
  get 'activities', to: 'bills#index'
  namespace :users do
	  get 'signup', to: 'registrations#new'
    post 'signup', to: 'registrations#create'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

end

app/models/bill.rb
# == Schema Information
#
# Table name: bills
#
#  id         :integer          not null, primary key
#  title      :string
#  amount     :float
#  author_id  :integer          not null
#  group_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Bill < ApplicationRecord

  validates :title, :amount, presence: true

  belongs_to :author, primary_key: :id, class_name: 'User'
  belongs_to :group
  has_many :members, through: :group
  has_many :splits, dependent: :destroy

  after_create :split_bill_amount

  scope :group_id_equals, ->(group_id) { where(group_id: group_id) }

  delegate :name, to: :author, prefix: true, allow_nil: true
  delegate :name, to: :group, prefix: true, allow_nil: true

  private

  # Splits the bill amount equally to group member.
  #
  # @return [void]
  def split_bill_amount
    members.each { |member| splits.create(split_attrs(member.id)) }
  end

  # Attributes (amount, member_type and recipient_id) required for splits
  #
  # @return [Hash]
  def split_attrs(member_id)
    {
      amount: equally_shared_amount,
      member_type: is_author?(member_id) ? 'payer' : 'recipient',
      recipient_id: is_author?(member_id) ? nil : member_id
    }
  end

  # Returns amount shared for each member of group
  #
  # @return [Float]
  def equally_shared_amount
    amount / members.count
  end

  # Verifies whether member has payed bill.
  #
  # @param member_id [Integer]
  def is_author?(member_id)
    member_id == author.id
  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  before_action :require_user

  # Renders list of <tt>Bills</tt>.
  #
  # @verb GET
  #
  # @accepts HTML
  def index
    @bills = Bill.includes(:splits).paginate(page: params[:page], per_page: 5)
  end

  # Renders new form for <tt>Bill</tt>.
  #
  # @get_params :id
  #
  # @verb GET
  #
  # @accepts HTML
  def new
    @bill = Bill.new
  end

  # Creates new <tt>Bill</tt>.
  #
  # @get_params :id
  #
  # @verb POST
  #
  # @accepts HTML
  def create
    @bill = group.bills.build(author_id: current_user.id)
    @bill.assign_attributes(bill_params)
    if @bill.save
      flash[:notice] = t('.added_successfully')
      redirect_to group_path(id: group.id)
    else
      render :new
    end
  end

  private

  # Finds <tt>Group</tt> using params id.
  #
  # @return [Group]
  def group
    @group ||= Group.find params[:group_id]
  end

  # Only allow a list of trusted parameters through params white listing.
  def bill_params
    params.require(:bill).permit(:title, :amount)
  end

end

app/views/bills/index.html.haml
.container
  - @bills.each do |bill|
    .list-group
      %a.list-group-item.list-group-item-action.flex-column.align-items-start{href: '#'}
        .d-flex.w-100.justify-content-between
          %h5.mb-1= "#{bill.author_name} has paid #{bill.amount.round(2)}"
          %small= bill.created_at.strftime('%F')
        - bill.splits.each do |split|
          - unless split.recipient_id.nil?
            %p.mb-1= "#{split.amount.round(2)} is owed by #{split.debtor_name}"
        %small= "Group name - #{bill.group_name}"
.flickr_pagination.mb-4
  = will_paginate @bills, container: false

app/views/bills/new.html.haml
.container
  .row.justify-content-center
    .col-10
      = render 'shared/errors', obj: @bill
      = form_with(model: @bill, url: group_bills_path(group_id: params[:group_id]), class: 'shadow p-3 mb-3 bg-info rounded', local:true)  do |f|
        .form-group.row
          = f.label :title, class: 'col-2 col-form-label text-light'
          .col-10
            = f.text_field :title, class:'form-control shadow rounded'
        .form-group.row
          = f.label :amount, class: 'col-2 col-form-label text-light'
          .col-10
            = f.number_field :amount, class:'form-control shadow rounded'
        .form-group.row.justify-content-center
          = f.submit t('general.submit'), class: 'btn btn-outline-light btn-lg'
    = link_to '[ Cancel and return to Membership listing ]', group_path(params[:group_id]), class: 'text-info'