config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :groups, except: %i[edit update] do
    resources :memberships, only: %i[new create destroy]
    resources :bills, only: %i[new create]
  end
  get 'activities', to: 'bills#index'
  namespace :users do
	  get 'signup', to: 'registrations#new'
    post 'signup', to: 'registrations#create'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

end

app/views/layouts/_messages.html.haml
.container.mt-3
  - flash.each do |name, msg|
    %div{class: "alert alert-#{"#{name}"} alert-dismissible fade show", role: 'alert'}
      %a.close{ 'data-dismiss' => 'alert', href: '#' } ×
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-expand-lg.bg-secondary.navbar-dark.bg-dark
  .container
    = link_to t('general.bill_split'), root_path, class: 'navbar-brand'
    %button.navbar-toggler{'aria-controls' => 'navbarSupportedContent', 'aria-expanded' => 'false', 'aria-label' => 'Toggle navigation', 'data-target' => '#navbarSupportedContent', 'data-toggle' => 'collapse', type: 'button'}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        - if logged_in?
          %li.nav-item.active
            = link_to t('general.groups'), groups_path, class: 'nav-link'
          %li.nav-item.active
            = link_to t('general.activity'), activities_path, class: 'nav-link'
      %ul.navbar-nav.ml-auto
        - if logged_in?
          %li.nav-item
            = link_to t('general.logout'), users_logout_path, method: :delete, class:'btn btn-danger'
        - else  
          %li.nav-item
            = link_to t('general.login'), users_login_path, class: 'btn btn-secondary mb-2 mr-2'
          %li.nav-item
            = link_to t('general.sign_up'), users_signup_path, class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BillSplit
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navigation'
    = render 'layouts/messages'
    = yield